name: gitam
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.2
#   http: ^0.13.6
#   youtube_player_flutter: ^8.1.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  youtube_player_flutter: ^8.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
